### ISSUE TITLE
Loading GIF

### ISSUE THREAD

**Issue by AndreasWebdev** [torch2424/live-stream-radio#11]
Add a path variable in the config for a "loading gif" that get's always played while the stream is loading the next song with the interlude (instead of showing a random gif)

**Comment by torch2424** [comment]
That's a good idea! When I make my next batch of major updates I'll get that going :)

Feel free to fork and make a PR as well

**Comment by AndreasWebdev** [comment]
I still fight my way through the code, haven't done anything for linux yet but I begin to understand :smile:

**Comment by torch2424** [comment]
Nice! I am glad this is helping you out?

I am summing you do web development? Are you doing Javascript on Windows then?

**Comment by AndreasWebdev** [comment]
Yes, Frontend HTML, CSS, Javascript, Backend PHP MySQL and (lately) NodeJS.. Also Unity C# and Android Java

**Comment by torch2424** [comment]
Nice! I do all my work in Unix (I love Ubuntu, but currently on a mac for work), and I do mostly Node / ES6 work in Angular. I used to do some wordpress stuff for friends here and there. But this is just a fun side project of mine written in bash haha 😄

**Comment by AndreasWebdev** [comment]
I believe this is fixed by the interlude videos in the node-rebuild, right @torch2424 ?

**Comment by torch2424** [comment]
Yes! Sorry just saw this, going to close this.

And if this doesn't solve this, then definitely, #87 will 😄
